# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d299d63544e192da1ce32b65cda986e2480a79a0fa188d71d614d5816375a6447acefb477bcc36c830a3db07b8fdf69dc49a309916df76317443a3175b246085

test:
  secret_key_base: b75d8c80136358660aa7fd590b7b71fe16a854f6cab207732a58007346c65a3278d3f26a756b020362cf09b7c2ed32c0fe73aa9aeb5fb36b87eb53de65e75604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
